### PR TITLE
Added SVG image element

### PR DESCRIPTION
**Pull request by tonicebrian**
- I've added the image tag from SVG to the set of elements along related types
- There are lots of formatting changes because when working with LSP I have activated the lsp-formatting (purty) and reordering of imports. Let me know if you like the PR without those changes although IMHO they are good defaults and helps readability for other devs.
- Relevant changes for this PR
  - [Add image element ](https://github.com/JordanMartinez/purescript-halogen-svg-elems/compare/master...tonicebrian:feature/image-element?expand=1#diff-bbd44e4b15d8b7cb19963ee8226440dc749e00af97dfcb94f6f30f462f138621R29-R31)
  - [Add href attribute from SVG](https://github.com/JordanMartinez/purescript-halogen-svg-elems/compare/master...tonicebrian:feature/image-element?expand=1#diff-f222070a99beb077c4e0a9a66d8c66732600b9abb1a66a182e24a3c64170e3c2R397-R399)
  - [Add type for image attributes](https://github.com/JordanMartinez/purescript-halogen-svg-elems/compare/master...tonicebrian:feature/image-element?expand=1#diff-f899124e668635c7591ac47c018bde0f525fe74d4816f58834252510685a0100R125-R133)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
@tonicebrian I apologize. Apparently, I wasn't watching this repo (likely because it was a fork?) so I was never notified of your PR.

**Comment by JordanMartinez** [comment]
Yeah, I'd prefer we not do any of the formatting changes in this PR. That should be handled in a separate PR (as they do need to be done at some point).

**Comment by tonicebrian** [comment]
I'll try to undo the formatting and recreate the PR without the formatting.

**Comment by tonicebrian** [comment]
Hey @JordanMartinez I've done a couple of fixes and undo the formatting issues. I hope this can be merged now.

**Comment by JordanMartinez** [comment]
Thanks!

**Pull request merged**
